### ISSUE TITLE
Sprites / Arte

### ISSUE THREAD

**Issue by dimiro1** [LidiaYoshino/godot-platformer-programaria#1]

**Comment by LidiaYoshino** [comment]
Oi @dimiro1 por aqui tudo bem e por ai?
Eu peguei essas artes [desse site](https://opengameart.org/content/arcade-platformer-assets), estou usando só de placeholder, esse jogo faz parte de um projeto do [PrograMaria](https://www.programaria.org/) e tem outras meninas fazendo a parte das artes :)

Que legal!! Vou dar uma fuçada no seu projeto hehehe

Sempre gostei muito de jogos e curtia muito o MegaDrive do meu pai, boas lembranças :D
Quero brincar mais de fazer jogos daqui pra frente e adoraria trabalhar em um projeto desses com você!

Desculpa a demora pra responder, ainda sou bem noob do GitHub
